Specify a cffi version in requirements
pip3 requires cffi to have a version spec:

ValueError: ('Expected version spec in', 'pylibmodbus/setup.py', 'at', '/setup.py')